version: '3.8'

services:
  creds-frontend:
    build:
      context: ./Creds-frontend
      dockerfile: Dockerfile
    container_name: creds-frontend
    ports:
      - "3000:3000"
    depends_on:
      - creds-backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/data
    networks:
      - creds-secure-network
    restart: unless-stopped

  creds-backend:
    build:
      context: ./Creds-backend
      dockerfile: Dockerfile
    container_name: creds-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo-creds
    environment:
      - DB_CREDS_URL=mongodb://mongo-creds:27017/creds
    networks:
      - creds-secure-network
    restart: unless-stopped

  mongo-creds:
    image: mongo:latest
    container_name: mongoDB-creds
    ports:
      - "27018:27017"
    volumes:
      - mongo-creds-data:/data/db
    networks:
      - creds-secure-network
    restart: unless-stopped
  
  to-do-app:
    build:
      context: ./To-do-list
      dockerfile: Dockerfile
    # container_name: to-do-app
    # ports:
    #   - "8000:8000"
    depends_on:
      - mongo-todo
    environment:
      - DB_TODO_URL=mongodb://mongo-todo:27017/todo
    networks:
      - todo-network
    restart: unless-stopped

  mongo-todo:
    image: mongo:latest
    container_name: mongoDB-todo
    ports:
      - "27019:27017"
    networks:
      - todo-network
    restart: unless-stopped
  
  nginx-load-balancer:
    image: nginx:latest
    volumes: 
      - ./nginx-server/conf.d:/etc/nginx/conf.d
    depends_on:
      - to-do-app
    ports:
      - "8000:8000"
    networks:
      - todo-network
    restart: unless-stopped
    

volumes:
  mongo-creds-data:

networks:
  creds-secure-network:
  todo-network:
