# Use the official Node.js image from the Docker Hub
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY ./package*.json /app

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /app

EXPOSE 3000

# Specify the command to run the application
CMD ["npm", "start"]
